# Generated by Django 2.2 on 2021-09-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0002_comic_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='comic',
            field=models.ManyToManyField(related_name='comic_in_col', to='comic_app.Comic'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='notes',
            field=models.CharField(default='no notes to display', max_length=255),
        ),
    ]
