# Generated by Django 2.2 on 2021-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0003_auto_20210902_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='favorite',
        ),
        migrations.AddField(
            model_name='comic',
            name='favorite',
            field=models.ManyToManyField(related_name='a_fav', to='comic_app.User'),
        ),
    ]
