# Generated by Django 2.2 on 2021-09-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0005_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='comic',
            name='uploaded_by',
            field=models.ManyToManyField(related_name='uploader', to='comic_app.User'),
        ),
    ]
