# Generated by Django 2.2 on 2021-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0007_auto_20210906_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
