# Generated by Django 2.2 on 2021-09-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0008_auto_20210906_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='notes',
            field=models.CharField(default='No notes to display', max_length=255),
        ),
    ]
