from django.urls import path
from . import views

urlpatterns=[
    path('', views.login),
    path('register', views.register),
    path('login_val', views.login_val),
    path('reg_val', views.reg_val),
    path('success', views.success),
    # path('success_add_comic', views.success_add_comic),
    path('add_comic', views.add_comic),
    path('landing', views.landing),
    path('alpha_landing', views.alpha_landing), 
    path('rd_landing', views.rd_landing),
    path('logout', views.logout),
    path('<int:comic_id>/comic_detail', views.comic_detail),
    path('<int:comic_id>/add_note', views.add_note),
    path('home', views.home),
    path('<int:comic_id>/add_fav', views.add_fav),
    path('<int:comic_id>/un_fav', views.un_fav),
    path('fav_page', views.fav_page),
    path('alpha_favs', views.alpha_favs), 
    path('rd_fav_page', views.rd_fav_page),
    path('add_collection', views.add_collection),
    path('<int:collection_id>/add_to_collection', views.add_to_collection),
    path('<int:collection_id>/collection_detail', views.collection_detail),
    path('<int:collection_id>/alpha_collection_detail', views.alpha_collection_detail),
    path('<int:collection_id>/rd_collection_detail', views.rd_collection_detail),
    path('<int:collection_id>/un_to_collection', views.un_to_collection),
    path('<int:comic_id>/un_to_collection_in_collection', views.un_to_collection_in_collection),
    path('<int:collection_id>/collection_edit', views.collection_edit),
    path('<int:collection_id>/update_collection_name', views.update_collection_name), 
    path('<int:collection_id>/del_collection', views.del_collection), 
    path('del_conf', views.delete_conf), 
    path('<int:comic_id>/del_comic', views.del_comic), 
    path('del_conf_comic', views.del_conf_comic), 
    # path('<int:collection_id>/test', views.test), 
    path('<int:comic_id>/un_fav_fav_list', views.un_fav_fav_list),
    path('most_fav', views.most_fav),
    path('test', views.test)
]
